version: '3.8'

services:
    # Amplify フロントエンドサーバ
    amplify:
        build: ./amplify
        ports:
            - "8080:8080"
        volumes:
            - ./amplify/amplify-sample-project/:/var/www/app
            - ${USER_PATH}/.aws/:/root/.aws/
        tty: true
        stdin_open: true
        command: "npm run serve"
        # command: tail -f /dev/null    # エラー時の最小起動
        environment:
            - CHOKIDAR_USEPOLLING=true