version: '3.8'

services:
    # Amplify フロントエンドサーバ
    amplify:
        build: ./amplify
        ports:
            - "8080:8080"
        volumes:
            - ./amplify/amplify-sample-project/:/var/www/app
            - ~/.aws/:/root/.aws/
        tty: true
        command: "npm run serve"